# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28f098deeb0f296ef05f6a54bcb8cdc8b4cf5b5bc19f3e4caaa1dfabb11aef052f2e78aa2ee7568907e156846f3b66a45a9eef5a2e4fdb6841dd10c6ab1e8d22

test:
  secret_key_base: c5f39ee8ffc841bb08a9de56293c08a9ac0359b74ab0a544931d4da71946d1fa9927445a14ced854f67de0bc5d5b78be9a2dd80e3e435a9b688bd3e3543c1e59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>